### ISSUE TITLE
Not 10.4? I pulled the latest Docker image.. and version is still 10.1.43

### ISSUE THREAD

**Issue by gremo** [linuxserver/docker-mariadb#45]
Am I'm doing something wrong?

```yml
version: '3'

services:
    db:
        image: 'linuxserver/mariadb'
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: Europe/Rome
```
