### ISSUE TITLE
Support a sql dump for large files when initializing the container

### ISSUE THREAD

**Issue by thombou** [linuxserver/docker-mariadb#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Feature request

Currently, there is an option to initialize a database with a sql file when the container is initialized for the first time. However this method does not work for large sql files (mine is 1Mb for example). 
------------------------------

## Expected Behavior

I would expect that when the container starts for the first time, a command similar to `mysql my_db < my_sql_dump.sql` would be executed, even for large `.sql` files.

## Current Behavior
Currently this dump does not work in my case. There is only 1 table structure (and no data) being imported in the container. I suspect that there is no problem with the `.sql`file as when execute the command in the container manually, it works. I execute the following command : 
`mysql -p my_db < /config/initdb.d/my_sql_dump.sql`

## Steps to Reproduce

1. Copy a (potentially large) sql dump in `database/initdb`
2. Start container mounting `database` in `/config`

## Environment
**OS:**  Raspbian
**CPU architecture:** arm      
**How docker service was installed:**      
Installation through docker compose

## Command used to create docker container (run/create/compose/screenshot)
```
    db:
        image: linuxserver/mariadb:latest
        container_name: db
        ports:
            - 3308:3306
        volumes:
            - ./database:/config
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=my_db
        restart: always
```
