### ISSUE TITLE
arch/arm uses outdated version 10.1 of MariaDB

### ISSUE THREAD

**Issue by gabrielwhite** [linuxserver/docker-mariadb#60]
## Expected Behavior

When I pull linuxserver/mariadb:latest I would expect version 10.4 to be installed per the release notes.

## Current Behavior

linuxserver/mariadb:latest installs version 10.1.

```
mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

## Steps to Reproduce
1. run any docker-compose with linuxserver/mariadb:latest

## Environment
**OS:** OMV5 / Debian Buster      
**CPU architecture:** arm32      
**How docker service was installed:**      
Using OMV5's built-in installer

## Command used to create docker container (run/create/compose/screenshot)

```
version: "3"

services:
  db:
    image: linuxserver/mariadb:latest
    network_mode: bridge
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Santiago
      - MYSQL_DATABASE=somename
      - MYSQL_USER=somename
      - MYSQL_PASSWORD=abcd 
    volumes:
      - db_data:/config
    ports:
      - 3306:3306
    restart: unless-stopped
```
