### ISSUE TITLE
Armhf image has outdated MariaDB version: 10.1.47

### ISSUE THREAD

**Issue by SignumPL** [linuxserver/docker-mariadb#69]
If I understand correctly, changelog says that MariaDB version should be 10.4, but instead is 10.1.47. I did `docker-compose pull` and image seems to be up to date, but MariaDB version is still outdated.

## Environment
**OS:** Raspbian Buster
**CPU architecture:** arm32
**How docker service was installed:**
```
version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=****
      - TZ=Europe/Warsaw
      - MYSQL_USER=****
      - MYSQL_PASSWORD=****
    volumes:
      - /mnt/storage/mariadb:/config
    ports:
      - 3306:3306
    networks:
      - shared
    restart: unless-stopped
networks:
  shared:
    driver: bridge
```

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing...
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
210122 20:27:00 mysqld_safe Logging to syslog.
210122 20:27:00 mysqld_safe Starting mysqld daemon with databases from /config/databases
```
