### ISSUE TITLE
armhf alpine - docker container high CPU usage

### ISSUE THREAD

**Issue by SignumPL** [linuxserver/docker-mariadb#76]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Normal CPU usage.

## Current Behavior
100% CPU usage when idle.

## Steps to Reproduce
1. Create `docker-compose.yml` and paste the contents of the below yml config
2. Start with `docker-compose up`
3. Notice that fresh container, without any databases and connections, consumes 100% of CPU.

This behavior seems to affect only the new alpine image, previous image was working perfectly fine.

## Environment
**OS:** Raspbian Buster
**CPU architecture:** arm32
**docker-compose**
**Docker version 20.10.3**
**libseccomp2.4.4**

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.2"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:alpine
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Europe/Warsaw
      - MYSQL_USER=su
      - MYSQL_PASSWORD=1234
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing...
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
210215 20:18:16 mysqld_safe Logging to '/config/databases/a7fb56d21764.err'.
210215 20:18:16 mysqld_safe Starting mariadbd daemon with databases from /config/databases
```
