### ISSUE TITLE
Cannot connect to the mariadb database rpi4

### ISSUE THREAD

**Issue by gado070707** [linuxserver/docker-mariadb#94]
Hello,
I am trying desperately to connect to the mariadb database on raspberry pi 4 but I cannot. 
When I try to log into mariadb :

> docker-compose up -d
Creating mariadb ... done
docker exec -it mariadb mysql -h 127.0.0.1 -P 3306 -u root -p
Enter password:
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)

**ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)**

However my docker-compose.yml is extremely simple :

```
version:` "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/peter/docker/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
networks:
    backend:
        name: backend
        external: true
```

I am currently on raspberry pi 4 :

>uname -a
Linux monmaria 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux

```
Version de Debian
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Do you need more information ?
Do you have any idea what I'm doing wrong?

thanks in advance

Rudy
