### ISSUE TITLE
logging to syslog, but no syslog is running

### ISSUE THREAD

**Issue by jeffallen** [linuxserver/docker-mariadb#99]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I would like to be able to see the logs of mariadb. (#58 would also like to.)

## Current Behavior

On start, mariadb says, `mysqld_safe Logging to syslog`. So I should be able to go see it's logs in /var/log/syslog. But there are no logs, because there's no syslog server running to capture them and write them to a file.

What I'd like instead is that mysqld_safe and mysqld are both told to log to stdout, so that Docker manages their log messages. I can't figure out how to do that, because it seems like mysqld_safe does not read custom.cnf, only /etc/mysql/conf.d/mysqld_safe_syslog.cnf.

## Command used to create docker container (run/create/compose/screenshot)

Docker-compose:

```
version: "2"
services:
    nextcloud:
      image: linuxserver/nextcloud
      container_name: nextcloud
      environment:
        - PUID=1003 #change PUID if needed
        - PGID=100  #change PGID if needed
        - TZ=Europe/Paris #change Time Zone if needed
      volumes:
        - /vault/nextcloud/config:/config #/srv/dev-disk-by-label-disk1 needs to be adjusted
        - /vault/nextcloud/data:/data     #/srv/dev-disk-by-label-disk1 needs to be adjusted
      depends_on:
        - mariadb
      ports:
        - 9999:80
        - 9443:443
      restart: unless-stopped
    mariadb:
      image: linuxserver/mariadb
      container_name: nextclouddb
      environment:
        - PUID=1003 #change PUID if needed
        - PGID=100  #change PGID if needed
        - MYSQL_ROOT_PASSWORD=XXX
        - TZ=Europe/Paris #Change Time Zone if needed
      volumes:
        - /vault/nextcloud/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
      restart: unless-stopped
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1003
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-initialise-db: executing... 
[cont-init.d] 40-initialise-db: exited 0.
[cont-init.d] 90-warning: executing... 

******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image will soon be rebased           *
*               from ubuntu to alpine.               *
*       Please be aware, this may cause issues       *
*     It is strongly recommended to make backups     *
*         of your config and databases before        *
*       updating your image to the alpine base.      *
*                                                    *
*                                                    *
******************************************************
******************************************************
[cont-init.d] 90-warning: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
220210 14:06:34 mysqld_safe Logging to syslog.
220210 14:06:35 mysqld_safe Starting mysqld daemon with databases from /config/databases
```
